### ISSUE TITLE
Udoskonalić nagłówek strony

### ISSUE THREAD

**Issue by ad-m** [pilnujemy/pilnujemy.github.io#2]
Hej,

Nagłówek powinien wykorzystywać nasze logo i nasz krój pisma. Jeżeli nie masz - prześlę Ci.

Z poważaniem,

**Comment by mik-laj** [comment]
Proszę o przesłanie brakujących zasobów.

**Comment by ad-m** [comment]
Proszę http://files.jawne.info.pl/private_html/2015_11_cf95e397d22dd3162f36e76c4d914d389a0bb311
