### ISSUE TITLE
Budowanie aplikacji

### ISSUE THREAD

**Issue by mik-laj** [pilnujemy/pilnujemy.github.io#7]
Witam. 
Kilka zmian: 
1) Skasowanie katalogu z plikami statycznymi /theme/static
2) Włączenie do procesu budowania komendy npm install, a zatem skompilowanie zasobów i utworzenie katalogu /theme/static
https://github.com/pilnujemy/pilnujemy.github.io/blob/6180d0ad6e194880546df1712b9d1dfb983eae97/package.json#L9

Jest to o tyle ważne, żę pozbywamy się w ten sposób cudzego kodu z repo. Przykładowo, gdybyśmy chcieli skorzystać z jQuery to on pojawi się w /theme/static jego kopia, która ma dużo linijek i de facto zdominuje statystyki języków w naszym projekcie. Jest to wskazanie nie zalecane. Zależności frontendu powinny być pobierane tak jak biblioteki Pythona. Nie uważam, abyśmy powinni traktować je inaczej.

Pozdrawiam

**Comment by ad-m** [comment]
Nie wiem jak to by się miało budować. Z jakiegoś powodu się kładzie https://travis-ci.org/pilnujemy/pilnujemy.github.io/builds/90092847 .
